# Generated by Django 3.2 on 2021-05-03 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_recipes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 5, 3, 9, 17, 59, 680180, tzinfo=utc), upload_to='pictures/'),
        ),
    ]
