# Generated by Django 3.2 on 2021-05-03 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210503_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 5, 3, 15, 55, 48, 784484, tzinfo=utc), upload_to='pictures/'),
        ),
    ]
